[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@prisma/client/**/*",
    "prisma/schema.prisma",
    ".env*"
  ]
  
  [functions."*"]
    node_bundler = "esbuild"
