#!/bin/bash

echo "🔑 GitHub SSH Setup Instructions"
echo "=================================="
echo ""
echo "Your SSH public key has been generated. To complete the setup:"
echo ""
echo "1. Copy your SSH public key below:"
echo ""
echo "----------------------------------------"
cat ~/.ssh/id_ed25519.pub
echo "----------------------------------------"
echo ""
echo "2. Go to: https://github.com/settings/keys"
echo "3. Click 'New SSH key'"
echo "4. Title: 'FinFlow Tracker Development Machine'"
echo "5. Paste the key above"
echo "6. Click 'Add SSH key'"
echo ""
echo "After adding the key, test the connection with:"
echo "  ssh -T git@github.com"
echo ""
echo "To switch the repository to use SSH instead of HTTPS:"
echo "  cd ~/finflow-tracker"
echo "  git remote set-url origin git@github.com:Fern-Labs-Open-Source/finflow-tracker.git"
echo ""
echo "✅ Then you can push/pull without entering credentials!"
echo ""
echo "📝 Note: Commits will appear as:"
echo "  Author: Fern App (FinFlow Bot) <finflow-bot@fern-labs.ai>"
echo "  Committer: Your GitHub account (for authentication)"
echo ""
echo "This separates authorship (who wrote the code) from authentication (who has permission to push)."
