name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Weekly security check

jobs:
  # CRITICAL: Detect exposed secrets
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for comprehensive scanning
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check .env.example for secrets
        run: |
          if [ -f .env.example ]; then
            if grep -E "(password|secret|key|token)=.+" .env.example; then
              echo "❌ ERROR: .env.example contains values that look like secrets!"
              echo "The .env.example file should only contain empty templates."
              exit 1
            fi
          fi
      
      - name: Scan for hardcoded credentials
        run: |
          # Check for common secret patterns in code
          if grep -r "ADMIN_PASSWORD\|DATABASE_URL\|NEXTAUTH_SECRET\|API_KEY" \
             --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
             --exclude-dir=node_modules \
             --exclude-dir=.git \
             src/ 2>/dev/null | grep -v "process.env"; then
            echo "❌ ERROR: Found hardcoded secrets in source code!"
            exit 1
          fi
          echo "✅ No hardcoded secrets detected"

  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate || true
          # Get vulnerability count
          VULNS=$(npm audit --json | jq '.metadata.vulnerabilities.moderate + .metadata.vulnerabilities.high + .metadata.vulnerabilities.critical' || echo 0)
          if [ "$VULNS" -gt 0 ]; then
            echo "⚠️ Found $VULNS moderate or higher vulnerabilities"
            npm audit
          else
            echo "✅ No moderate or higher vulnerabilities found"
          fi
